name: release

on:
  workflow_dispatch:
    inputs:
      tag_to_create:
        description: "tag to create"
        default:
        required: true
        type: string

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: echo do the main code of getting the version established
      - name: version
        run: echo "::set-output name=version::$(echo test-1)"
        id: version
      - name: build artifacts
        run: echo build the tar files
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: true
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.event.inputs.tag_to_create }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload x86_64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./a.tar
          asset_name: azblogfilter.linux-amd64.tar
          asset_content_type: application/tar
